<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Bilgiler Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'cesbabadag@gmail.com',
		'to' => 'cesbabadag@gmail.com'
	),
	'fields' => array(
		'custom_U1196' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Takma Adınız',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Takma Adınız\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email address.'
			)
		),
		'custom_U1212' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Ünvan',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ünvan\' is required.'
			)
		),
		'custom_U1208' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Meslek',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Meslek\' is required.'
			)
		),
		'custom_U1216' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Yaş',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Yaş\' is required.'
			)
		),
		'custom_U1204' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Boy',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Boy\' is required.'
			)
		),
		'custom_U1188' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Vücut yapısı',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Vücut yapısı\' is required.'
			)
		),
		'custom_U1379' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Ülke',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ülke\' is required.'
			)
		),
		'custom_U1391' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Yaşadığınız şehir',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Yaşadığınız şehir\' is required.'
			)
		),
		'custom_U1415' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Hobileriniz',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Hobileriniz\' is required.'
			)
		),
		'custom_U1427' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Ön yazınız',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ön yazınız\' is required.'
			)
		),
		'custom_U1318' => array(
			'order' => 8,
			'type' => 'radiogroup',
			'label' => 'Medeni durum',
			'required' => true,
			'optionItems' => array(
				'Bekar',
				'Boşanmış'
			),
			'errors' => array(
				'required' => 'Field \'Medeni durum\' is required.',
				'format' => 'Field \'Medeni durum\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
